import type {MenuCategory} from './types'

export const menu: MenuCategory[] = [
    {
        id: 'pizza',
        name: 'Pizza',
        sizes: ['Klein', 'Groß', 'Family'],
        items: [
            {id: '1', name: '1. Margeritha', description: 'Käse', price: ['4,50', '7,20', '28,00'], locations: '*'},
            {id: '2', name: '2. Cipolla', description: 'Käse, Zwiebeln', price: ['4,90', '7,60', '30,00'], locations: '*'},
            {id: '3', name: '3. Carciofi', description: 'Käse, Artischocken', price: ['5,10', '8,10', '32,30'], locations: '*'},
            {id: '4', name: '4. Napoli', description: 'Käse, Sardellen, Oliven', price: ['5,30', '8,30', '32,50'], locations: '*'},
            {id: '5', name: '5. Paprika', description: 'Käse, Paprika', price: ['4,90', '7,60', '30,00'], locations: '*'},
            {id: '6', name: '6. Funghi', description: 'Käse, Champignons', price: ['4,90', '7,60', '30,00'], locations: '*'},
            {id: '7', name: '7. Salami', description: 'Käse, Salami', price: ['5,80', '8,60', '34,50'], locations: '*'},
            {id: '8', name: '8. Prosciutto', description: 'Käse, Kochschinken', price: ['5,80', '8,60', '34,50'], locations: '*'},
            {id: '9', name: '9. Tonno', description: 'Käse, Thunfisch', price: ['6,30', '9,70', '38,50'], locations: '*'},
            {id: '10', name: '10. Primavera', description: 'Käse, Thunfisch, Zwiebeln', price: ['7,20', '10,80', '43,00'], locations: '*'},
            {id: '11', name: '11. Hawaii', description: 'Käse, Kochschinken, Ananas', price: ['6,30', '9,30', '37,00'], locations: '*'},
            {id: '12', name: '12. Sofia', description: 'Käse, Kochschinken, Champignons', price: ['6,30', '9,30', '37,00'], locations: '*'},
            {id: '13', name: '13. Vulcano', description: 'Käse, Kochschinken, Salami', price: ['6,30', '9,30', '37,00'], locations: '*'},
            {id: '14', name: '14. Sola', description: 'Käse, Spargel, Champignons, Ei', price: ['6,40', '9,90', '39,50'], locations: '*'},
            {id: '15', name: '15. Italia', description: 'Käse, Paprika, Salami, Champignons', price: ['6,70', '9,90', '39,50'], locations: '*'},
            {id: '16', name: '16. Regina', description: 'Käse, Kochschinken, Salami, Champignons', price: ['6,70', '9,90', '39,50'], locations: '*'},
            {id: '17', name: '17. Quattro Stagioni', description: 'Käse, Kochschinken, Thunfisch, Champignons, Paprika', price: ['7,20', '10,70', '43,00'], locations: '*'},
            {id: '18', name: '18. Mista', description: 'Käse, Kochschinken, Salami, Champignons, Paprika', price: ['7,20', '10,70', '43,00'], locations: '*'},
            {id: '19', name: '19. Calzone', description: 'Käse, Kochschinken, Champignons, Thunfisch, Artischocken', price: ['', '10,80', ''], locations: '*'},
            {id: '20', name: '20. Marinara', description: 'Käse, Meeresfrüchte', price: ['6,60', '9,90', '39,00'], locations: '*'},
            {id: '21', name: '21. Venezia', description: 'Käse, Kochschinken, Thunfisch, Ananas', price: ['7,20', '10,70', '43,00'], locations: '*'},
            {id: '22', name: '22. Scampi', description: 'Käse, Krabben', price: ['6,60', '9,90', '39,00'], locations: '*'},
            {id: '23', name: '23. Bella Napoli', description: 'Käse, Salami, Champignons, Paprika, Artischocken, Ei', price: ['7,20', '10,70', '43,00'], locations: '*'},
            {id: '25', name: '25. Salami-Funghi', description: 'Käse, Salami, Champignons', price: ['6,30', '9,30', '37,00'], locations: '*'},
            {id: '26', name: '26. Salami Cipolla', description: 'Käse, Salami, Zwiebeln', price: ['6,30', '9,30', '37,00'], locations: '*'},
            {id: '27', name: '27. Prosciutto Cipolla', description: 'Käse, Kochschinken, Zwiebeln', price: ['6,30', '9,30', '37,00'], locations: '*'},
            {id: '28', name: '28. Spinat', description: 'Käse, Spinat', price: ['5,30', '8,20', '32,00'], locations: '*'},
            {id: '29', name: '29. Bolognese', description: 'Käse, hausgemachte Bolognesesauce', price: ['6,40', '8,80', '35,50'], locations: '*'},
            {id: '30', name: '30. Romantica', description: 'Käse, Kochschinken, Salami, Artischocken', price: ['6,40', '9,80', '39,50'], locations: '*'},
            {id: '31', name: '31. Milano', description: 'Käse, Thunfisch, Spinat, Ei', price: ['7,20', '10,70', '43,00'], locations: '*'},
            {id: '32', name: '32. Crossa', description: 'Salat, Tomaten, Gurken, Krautsalat, gegrillte Hähnchenbrust, Knoblauchsauce', price: ['8,60', '12,00', ''], locations: '*'},
            {id: '33', name: '33. Patchino', description: 'Käse, Kochschinken, Champignons, Thunfisch', price: ['7,20', '10,70', '43,00'], locations: '*'},
            {id: '46', name: '46. Broccoli', description: 'Käse, Broccoli', price: ['5,30', '8,20', '32,00'], locations: '*'},
            {id: '47', name: '47. Marco', description: 'Käse, Kochschinken, Broccoli', price: ['6,30', '9,30', '37,00'], locations: '*'},
            {id: '48', name: '48. Vera Picante', description: 'Käse, Bolognesesauce, Kidney Bohnen, Mais, Jalapenos', price: ['6,90', '9,50', '39,60'], locations: '*'},
            {id: '49', name: '49. Gyros', description: 'Käse, Gyros, Zwiebeln, Jalapenos, frische Tomaten, Knoblauchsauce', price: ['8,80', '12,20', '48,50'], locations: '*'},
            {id: '50', name: '50. Mozzarella', description: 'Käse, frische Tomaten, Mozarella, Basilikum', price: ['6,30', '9,30', '37,00'], locations: '*'},
            {id: '51', name: '51. Gemüse', description: 'Zwiebeln, Paprika, Champignons, Mozzarella, Käse, Krautsalat, Knoblauchsauce', price: ['7,30', '10,60', '42,50'], locations: '*'},
            {id: '52', name: '52. Crossa Tonno', description: 'dünner Knoblauchteig mit Thunfisch, Salat, Tomaten, Gurken, Krautsalat, Knoblauchsauce', price: ['7,30', '11,00', ''], locations: '*'},
            {id: '53', name: '53. 4 Formaggi', description: '4 verschiedene Käsesorten', price: ['6,40', '9,90', '39,50'], locations: '*'},
            {id: '54', name: '54. Nello', description: 'Käse, Rigatoni, Bolognesesauce, Kochschinken', price: ['7,00', '10,50', '42,00'], locations: '*'},
            {id: '57', name: '57. Bacon', description: 'Käse, Bacon', price: ['5,80', '8,60', '34,50'], locations: '*'},
            {id: '58', name: '58. Egg & Bacon', description: 'Käse, Bacon, Ei', price: ['6,60', '9,50', '37,50'], locations: '*'},
            {id: '59', name: '59. Diablo', description: 'Peperonisalami, scharfe Peperoni, Tabasco, Mozzarella Käse', price: ['6,50', '9,50', '38,00'], locations: '*'},
            {id: '60', name: '60. Parma e Rucola', description: 'Mozzarella Käse, Parmaschinken, Rucola, Parmesankäse', price: ['8,20', '12,30', '49,50'], locations: '*'},
            {id: '61', name: '61. Rucola', description: 'Mozzarella Käse, Rucola', price: ['4,90', '7,90', '32,00'], locations: '*'},
            {id: '62', name: '62. Pollo', description: 'Käse, Broccoli, Hollandaisesauce, Hähnchen', price: ['7,90', '11,80', '47,50'], locations: '*'},
            {id: '63', name: '63. Salmone', description: 'Käse, Wildlachs, Spinat, Knoblauch', price: ['10,40', '13,20', '53,50'], locations: '*'},
            {id: '64', name: '64. Bacon+Plum', description: 'Käse, Pflaumen, Bacon', price: ['7,20', '10,30', '42,00'], locations: '*'},
        ],
    },
    {
        id: 'pasta-in-padella',
        name: 'Pasta in Padella',
        items: [
            {id: '100', name: '100. Spaghetti Napoli', description: 'mit Tomatensoße', price: '6,60', locations: '*'},
            {id: '101', name: '101. Spaghetti Bolognese', description: 'mit Hackfleischsoße', price: '7,40', locations: '*'},
            {id: '139', name: '139. Spaghetti Carbonara', description: 'mit Ei, Schinken, Sahnesoße, Parmesankäse', price: '10,50', locations: '*'},
            {id: '103', name: '103. Spaghetti Con Pesto', description: 'mit hausgemachtem Pesto und Parmesan', price: '8,30', locations: '*'},
            {id: '104', name: '104. Tortellini Napoli', description: 'Fleischfüllung, mit Tomatensoße', price: '8,80', locations: '*'},
            {id: '105', name: '105. Tortellini Bolognese', description: 'Fleischfüllung, mit Hackfleischsoße', price: '9,90', locations: '*'},
            {id: '106', name: '106. Tortellini alla Casa', description: 'Fleischfüllung, mit Schinken & Sahnesoße', price: '10,40', locations: '*'},
            {id: '107', name: '107. Rigatoni Napoli', description: 'mit Tomatensoße', price: '7,40', locations: '*'},
            {id: '108', name: '108. Rigatoni Bolognese', description: 'mit Hackfleischsoße', price: '8,30', locations: '*'},
            {id: '109', name: '109. Rigatoni alla Panna', description: 'mit Schinken & Sahnesoße', price: '8,70', locations: '*'},
        ],
    },
    {
        id: 'pasta-al-forno',
        name: 'Pasta al Forno',
        items: [
            {id: '134', name: '134. Rigatoni al Forno', description: 'mit Fleischsoße, Schinken, Champignons', price: '9,20', locations: '*'},
            {id: '135', name: '135. Tortellini al Forno', description: 'mit Hackfleischsoße, Schinken', price: '10,90', locations: '*'},
            {id: '136', name: '136. Nudelauflauf', description: 'versch. Nudelsorten mit Schinken, Hackfleischsoße, Spinat, Champignons und Käse überbacken', price: '11,00', locations: '*'},
            {id: '137', name: '137. Lasagne al Forno', description: 'Breitbandnudeln mit Fleischsoße, Schinken, Champignons', price: '11,00', locations: '*'},
            {id: '138', name: '138. Spaghetti al Forno', description: 'mit Hackfleischsoße', price: '8,60', locations: '*'},
            {id: '141', name: '141. Tortellini alla Panna', description: 'mit Schinken, Sahnesoße', price: '11,00', locations: '*'},
            {id: '142', name: '142. Tortellini alla Gorgonzola', description: 'mit Schinken, Sahnesoße & 4 Käsesorten überbacken', price: '11,60', locations: '*'},
        ],
    },
    {
        id: 'wraps',
        name: 'Wraps',
        items: [
            {id: '600', name: '600. Tonno Wrap', description: 'Thunfisch, Knoblauchöl, Käse, Salat, Tomaten, Gurken, Krautsalat, Knoblauchsauce, Zwiebeln', price: '8,50', locations: '*'},
            {id: '601', name: '601. Hähnchen Wrap', description: 'gegrillte Hähnchenbrust, Knoblauchöl, Salat, Käse, Tomaten, Gurken, Krautsalat, Knoblauchsauce', price: '8,50', locations: '*'},
            {id: '602', name: '602. Mozzarella Wrap', description: 'hausgemachtes Pesto, Mozzarella, Salat, Käse, Rucola, Tomaten, Gurken, Knoblauchsauce', price: '8,50', locations: '*'},
            {id: '603', name: '603. Parma Wrap', description: 'hausgemachtes Pesto, Käse, Parmaschinken, Salat, Rucola, Tomaten, Knoblauchsauce', price: '8,50', locations: '*'},
            {id: '605', name: '605. Crispy Chicken Wrap', description: 'Chicken-Fingers, Knoblauchöl, Eisbergsalat, Krautsalat, Tomaten, Gurken, Knoblauchsauce', price: '8,50', locations: '*'},
            {id: '606', name: '606. Greco Wrap', description: 'Gyros, Knoblauchöl, Käse, Salat, Zwiebeln, Feta Käse, Knoblauchsauce', price: '8,50', locations: '*'},
            {id: '607', name: '607. Vegan Wrap', description: 'Eisbergsalat, Rucola, Basilikum-Pesto, Edamame, rote Zwiebeln, Mais, Paprika, Granatapfelkerne, hausgemachtes veganes Joghurt-Dressing', price: '9,00', locations: '*'},
        ],
    },
    {
        id: 'salate',
        name: 'Salate',
        sizes: ['Klein', 'Groß'],
        items: [
            {id: '239', name: '239. Italiana', description: 'Kochschinken, Ananas, fr. Paprika, Käse und Oliven', price: ['5,80', '7,50'], locations: '*'},
            {id: '240', name: '240. Roma', description: 'Kochschinken, Thunfisch, Ananas, fr. Paprika, Käse und Oliven', price: ['6,40', '9,10'], locations: '*'},
            {id: '241', name: '241. Siziliana', description: 'Kochschinken, Thunfisch, Pilze, Zwiebeln, Spargel, fr. Paprika, Käse und Oliven', price: ['7,20', '9,70'], locations: '*'},
            {id: '242', name: '242. Verona', description: 'Mais und Karotten', price: ['5,10', '7,10'], locations: '*'},
            {id: '244', name: '244. Chefsalat', description: 'Mais, Zwiebeln, fr. Paprika und Käse', price: ['5,30', '7,50'], locations: '*'},
            {id: '246', name: '246. Mexicana', description: 'Kidney Bohnen, Mais, Käse und Ei', price: ['5,90', '8,00'], locations: '*'},
            {id: '247', name: '247. Toscana', description: 'Zwiebeln, fr. Paprika, Oliven, milde Peperoni, Weißkäse und Essig & Öl', price: ['5,90', '8,00'], locations: '*'},
            {id: '248', name: '248. Della Casa', description: 'Mais, Ananas, gegrillte Hähnchenbrust', price: ['7,20', '9,90'], locations: '*'},
            {id: '249', name: '249. Fitness Salat', description: 'Thunfisch, Ei, frische Paprika, gegrillte Hähnchenbrust, Joghurt-Dillsauce', price: ['8,30', '11,00'], locations: '*'},
        ],
    },
    {
        id: 'antipasti',
        name: 'Antipasti',
        items: [
            {id: '80', name: '80. Brötchen mit Kräuterbutter', price: '2,60', locations: '*'},
            {id: '84', name: '84. Brötchen Knoblauchsauce', price: '2,60', locations: '*'},
            {id: '85', name: '85. Gefüllte Brötchen Schinken', description: 'mit Kochschinken und Käse', price: '5,80', locations: '*'},
            {id: '86', name: '86. Gefüllte Brötchen Salami', description: 'mit Salami und Käse', price: '5,80', locations: '*'},
            {id: '87', name: '87. Gefüllte Brötchen Thunfisch', description: 'mit Thunfisch und Käse', price: '6,10', locations: '*'},
            {id: '88', name: '88. Gefüllte Brötchen Käse', description: 'mit Käse', price: '5,30', locations: '*'},
            {id: '89', name: '89. Bruschetta', price: '5,50', locations: '*'},
            {id: '82', name: '82. Kräuterbutter', price: '1,40', locations: '*'},
            {id: '83', name: '83. Knoblauchsauce', price: '1,40', locations: '*'},
            {id: '184', name: '184. Spicysauce', price: '1,40', locations: '*'},
            {id: '504', name: '504. Chicken Fingers', description: 'kleine / große Portion', price: ['5,30', '7,40'], locations: '*'},
            {id: '300', name: '300. Pizzabrot', description: 'im Ofen frisch gebacken mit Käse und Kräutern, wahlweise mit Kräuterbutter oder Knoblauchsauce', price: '6,60', locations: ['weseke']},
            {id: '300', name: '300. Pizzabrot', description: 'im Ofen frisch gebacken mit Käse und Kräutern, wahlweise mit Kräuterbutter oder Knoblauchsauce', price: '6,00', locations: ['borken']},
        ],
    },
    {
        id: 'desserts',
        name: 'Desserts',
        items: [
            {id: '400', name: '400. Tiramisu', description: 'mit Kaffee getränkter Biskuitboden, bedeckt mit einer Kaffee- und Zabaionecreme, besiebt mit Kakaopulver', price: '5,00', locations: '*'},
            {id: '401', name: '401. Cheesecake', description: 'Biskuitboden bedeckt mit einer Käsekuchen-Creme und fruchtiger Erdbeersauce', price: '5,00', locations: '*'},
            {id: '410', name: '410. Zimtis', description: 'gebackene Teigschnecken mit Zimt und Zucker', price: '4,50', locations: '*'},
        ],
    },
    {
        id: 'getraenke',
        name: 'Getränke & Biere',
        items: [
            {id: 'drink-soft-1l', name: 'Softdrinks', description: 'Cola, Cola Zero, Fanta, Sprite, Mezzo Mix · 1 l · zzgl. Pfand', price: '4,00', locations: '*'},
            {id: 'drink-wasser', name: 'Wasser (San Pelligrino)', description: '0,75 l · zzgl. Pfand', price: '5,00', locations: '*'},
            {id: 'drink-fassbrause', name: 'Fassbrause (Mango Maracuja)', description: '0,33 l · zzgl. Pfand', price: '2,80', locations: '*'},
            {id: 'bier-alkoholfrei', name: 'Alkoholfreie Biere', description: 'Vita Malz, Veltins alkoholfrei, Radler alkoholfrei · 0,33 l · zzgl. Pfand', price: '2,80', locations: '*'},
            {id: 'bier-veltins-weseke', name: 'Biere', description: 'Veltins, Alt, Radler, Grevensteiner Landbier · 0,33 l · zzgl. Pfand', price: '2,80', locations: ['weseke']},
            {id: 'bier-maisels', name: 'Weizenbiere', description: 'Maisels Weisse, auch alkoholfrei · 0,5 l · zzgl. Pfand', price: '4,00', locations: ['weseke']},
            {id: 'drink-soft-033', name: 'Softdrinks', description: 'Cola, Cola Zero, Fanta, Sprite, Mezzo Mix · 0,33 l · zzgl. Pfand', price: '2,80', locations: ['borken']},
            {id: 'bier-veltins-borken', name: 'Biere', description: 'Veltins, Alt, Radler · 0,33 l · zzgl. Pfand', price: '2,80', locations: ['borken']},
            {id: 'bier-erdinger', name: 'Weizenbiere', description: 'Erdinger, auch alkoholfrei · 0,5 l · zzgl. Pfand', price: '4,00', locations: ['borken']},
        ],
    },
]

/* Menu for one location: keeps only its items, drops categories that end up empty */
export function getMenuForLocation(locationId: string): MenuCategory[] {
    return menu
        .map((category) => ({
            ...category,
            items: category.items.filter((item) => item.locations === '*' || item.locations.includes(locationId)),
        }))
        .filter((category) => category.items.length > 0)
}
